osx_image: xcode8.1
language: objective-c
cache:
	- bundler
	- cocoapods
branches:
	only:
		- develop
		- master
notifications:
	emails: false
before_install:
	- gem install fastlane
	- bundle install
script:
	- bundle exec fastlane bonjour	